var firstname; firstname = "Reginaldo";
var lastname; lastname = "Campos de Souza";
var age; age = "33";
var dateOfBirth; dateOfBirth = "09/02/1991";
var address; address = "108 Shawville Place SE";
console.log("firstname: ", firstname);
console.log("lastname: ", lastname);
console.log("age: ", age);
console.log("dateOfBirth: ", dateOfBirth);
console.log("address: ", address);