let firstname; firstname = "Reginaldo";
let lastname; lastname = "Campos de Souza";
let age; age = "33";
let dateOfBirth; dateOfBirth = "09/02/1991";
let address; address = "108 Shawville Place SE";
console.log("firstname: ", firstname);
console.log("lastname: ", lastname);
console.log("age: ", age);
console.log("dateOfBirth: ", dateOfBirth);
console.log("address: ", address);